# Generated by Django 4.1.1 on 2022-11-08 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialapp', '0002_rename_up_vote_posts_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
